// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "new-york": {
    "field": {
      name: "field",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/new-york/ui/field.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/new-york/ui/field.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "field-demo": {
      name: "field-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["field"],
      files: [{
        path: "registry/new-york/example/field-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/new-york/example/field-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "login-01": {
      name: "login-01",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/new-york/block/login-01/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/new-york/block/login-01/components/login-form.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/new-york/block/login-01/page.tsx")),
      source: "__registry__/new-york/block/login-01/page.tsx",
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/new-york/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/new-york/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/new-york/hooks/use-mobile.tsx",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/new-york/hooks/use-mobile.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },  "default": {
    "field": {
      name: "field",
      description: "",
      type: "registry:ui",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/ui/field.tsx",
        type: "registry:ui",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/ui/field.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "field-demo": {
      name: "field-demo",
      description: "",
      type: "registry:example",
      registryDependencies: ["field"],
      files: [{
        path: "registry/default/example/field-demo.tsx",
        type: "registry:example",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/example/field-demo.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "login-01": {
      name: "login-01",
      description: "",
      type: "registry:block",
      registryDependencies: ["button","card","input","label"],
      files: [{
        path: "registry/default/block/login-01/page.tsx",
        type: "registry:page",
        target: "app/login/page.tsx"
      },{
        path: "registry/default/block/login-01/components/login-form.tsx",
        type: "registry:component",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/block/login-01/page.tsx")),
      source: "__registry__/default/block/login-01/page.tsx",
      category: "Authentication",
      subcategory: "Login",
      chunks: []
    },
    "utils": {
      name: "utils",
      description: "",
      type: "registry:lib",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/lib/utils.ts",
        type: "registry:lib",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
    "use-mobile": {
      name: "use-mobile",
      description: "",
      type: "registry:hook",
      registryDependencies: undefined,
      files: [{
        path: "registry/default/hooks/use-mobile.tsx",
        type: "registry:hook",
        target: ""
      }],
      component: React.lazy(() => import("@/registry/default/hooks/use-mobile.tsx")),
      source: "",
      category: "",
      subcategory: "",
      chunks: []
    },
  },
}
